import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function TopNav() {
  return(
    <nav className="flex items-center justify-between border-b p-4 text-xl font-semibold">
      <div> Gallery </div>

      <div> Sign In </div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.className} flex flex-col gap-4 ` } >
        <TopNav />
        {children}
      </body>
    </html>
  );
}
